name: Generate Snake Animation

on:
  # Executa automaticamente todos os dias às 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Permite rodar o workflow manualmente pela aba Actions
  workflow_dispatch:

  # Executa a cada push na branch principal
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Gera o gráfico SVG com a cobrinha comendo os commits
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#38bdf8&color_dots=#1e1f22,#0e4429,#006d32,#26a641,#39d353
      # Faz o deploy do SVG gerado para a branch 'output'
      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
